### ISSUE TITLE
How to change TextColor

### ISSUE THREAD

**Issue by hyunwook13** [Upstarts/editor.js-kit-ios#25]
How to change Text Color
I changed every text color in file to white color 
but the text color did't changed 
Plz Let know

**Comment by ivanglushko** [comment]
@Hyunwok 
Hi there! 
We would need a bit of context here 😄 

- **What data do you have?**
- **What do you expect to happen?**
- **What have you done in order to achieve it?**

**Comment by hyunwook13** [comment]
i Fixed it 
:)

**Comment by ivanglushko** [comment]
> i Fixed it
> :)

Awesome happy to hear that 😉
